In [1]:
import numpy as np
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.impute import KNNImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv('train.csv' , usecols=['Age' , 'Pclass' , 'Fare' , 'Survived'])

In [3]:
df.head()

   Survived  Pclass   Age     Fare
0         0       3  22.0   7.2500
1         1       1  38.0  71.2833
2         1       3  26.0   7.9250
3         1       1  35.0  53.1000
4         0       3  35.0   8.0500

In [4]:
x = df.drop(columns=['Survived'])
y = df['Survived']

x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [9]:
knn = KNNImputer(weights='distance' , n_neighbors=3)
x_train_knn = knn.fit_transform(x_train)
x_test_knn = knn.transform(x_test)

In [7]:
pd.DataFrame(x_train_knn,columns=x_train.columns)

     Pclass   Age      Fare
0       1.0  40.0   27.7208
1       3.0   4.0   16.7000
2       3.0  47.0    9.0000
3       3.0   9.0   31.3875
4       3.0  20.0    9.8458
..      ...   ...       ...
707     3.0  30.0    8.6625
708     3.0  24.2    8.7125
709     1.0  71.0   49.5042
710     1.0  28.0  221.7792
711     1.0  42.8   25.9250

[712 rows x 3 columns]

In [10]:
lr = LogisticRegression()
lr.fit(x_train_knn , y_train)
y_pred = lr.predict(x_test_knn)
accuracy_score(y_test,y_pred)

0.7039106145251397