In [14]:
import numpy as np
import pandas as pd
df = pd.read_csv('covid_toy.csv')
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

# Train Test split

In [15]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(df.drop('has_covid' , axis=1) , df['has_covid'] , test_size= 0.2 , random_state=0)
x_train.shape , x_test.shape

((80, 5), (20, 5))

In [24]:
df['fever'].isnull().sum # so fever column have 10 missing values

<bound method Series.sum of 0     False
1     False
2     False
3     False
4     False
      ...
95    False
96    False
97    False
98    False
99    False
Name: fever, Length: 100, dtype: bool>

# Aam Zindagi

In [25]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
# adding simple imputer to fever col
si = SimpleImputer()
x_train_fever = si.fit_transform(x_train[['fever']]) # it will replace all missing values by it's mean value of column.
# also test data
x_test_fever = si.fit_transform(x_test[['fever']])
x_train_fever.shape

(80, 1)

In [ ]:
#Ordinal Encoding -> cough
oe = OrdinalEncoder(categories=[['Mild' , 'Strong']])
x_train_cough = oe.fit_transform(x_train[['cough']])
#also test one
x_test_cough = oe.fit_transform(x_test[['cough']])
x_train_cough.shape

(80, 1)

In [48]:
#One Hot Encodinf -> gender , city
ohe = OneHotEncoder(drop='first')
x_train_gender_city = ohe.fit_transform(x_train[['gender' , 'city']]).toarray()
#one test data also
x_test_gender_city = ohe.fit_transform(x_test[['gender' , 'city']]).toarray()
x_test_gender_city.shape , x_train_gender_city.shape

((20, 4), (80, 4))

In [49]:
#Extracting age
x_train_age = x_train.drop(columns=['gender' ,'fever', 'cough' , 'city'])
x_test_age = x_test.drop(columns=['gender' ,'fever', 'cough' , 'city'])
x_train_age

    age
43   22
62   56
3    31
71   75
45   72
..  ...
96   51
67   65
64   42
47   18
44   20

[80 rows x 1 columns]

In [53]:
# conatenate everone 
x_train_transformed = np.concatenate((x_train_age , x_train_fever , x_train_gender_city, x_train_cough ), axis=1)
#test one also 
x_test_transformed = np.concatenate((x_test_age , x_test_fever , x_test_gender_city, x_test_cough ), axis=1)
x_train_transformed.shape

(80, 7)

# Mentos Zindagi by Column transform

In [64]:
from sklearn.compose import ColumnTransformer
transformer = ColumnTransformer(transformers=[
    ('tnf1' , SimpleImputer() , ['fever']),
    ('tnf2' , OrdinalEncoder(categories=[['Mild' ,'Strong']]) , ['cough']),
    ('tnf3', OneHotEncoder(sparse_output=False ,drop='first') , ['gender' , 'city'])
] , remainder='passthrough')

In [66]:
transformer.fit_transform(x_train).shape , transformer.fit_transform(x_test).shape

((80, 7), (20, 7))